name: build_and_push
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - uses: actions/checkout@v2

    # install go  
    - uses: actions/setup-go@v2.0.3
      with:
        go-version: '1.14'
        
    # build tools
    - name: build tarball
      run: |
        ./release.sh

    # upload to release
    - name: upload tarball to release
      run: |
        curl --data-binary @cli-tools-linux.tar.gz  \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/gzip" \
          'https://uploads.github.com/repos/marshians/cli-tools/releases/25649565/assets?name=cli-tools-linux.tar.gz'
