name: build_and_push
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

# This job can take more than an hour, so we use a PAT as the token
# for authentication.
# See: https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - uses: actions/checkout@v2

    # install go  
    - uses: actions/setup-go@v2.0.3
      with:
        go-version: '1.14'
        
    # build tools
    - name: build tarball
      run: |
        ./release.sh

    # delete our previous release
    - name: delete release
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        export BASE_URL="https://api.github.com/repos/marshians/cli-tools/releases"
        export RELEASE_ID=$(curl -s "$BASE_URL/latest"  | jq '.id')
        echo "$BASE_URL/$RELEASE_ID"
        curl -H "Authorization: token $TOKEN" -s -X DELETE "$BASE_URL/$RELEASE_ID"

    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: master
        release_name: master
        draft: false
        prerelease: false

    - name: upload tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cli-tools.tar.gz
        asset_name: cli-tools.tar.gz
        asset_content_type: application/gzip
